#!/usr/bin/env node
// Emits js/config.js from `terraform output -json` read on stdin.
//
// Usage:
//   cd bird-count-backend
//   make tf CMD='output -json' | node ../bird-count-web/scripts/make-config.mjs          # deployed URL
//   make tf CMD='output -json' | node ../bird-count-web/scripts/make-config.mjs --local  # localhost:8788

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const isLocal = process.argv.includes('--local');

let raw = '';
for await (const chunk of process.stdin) raw += chunk;

const tf = JSON.parse(raw);
const get = key => tf[key]?.value ?? tf[key];

const apiBaseURL    = (get('api_url') ?? '').replace(/\/$/, '');
const hostedUIDomain = get('hosted_ui_domain');
const webClientId   = get('web_client_id');
const websiteURL    = (get('website_url') ?? '').replace(/\/$/, '');
const redirectURI   = isLocal ? 'http://localhost:8788/' : `${websiteURL}/`;

const src = `// GENERATED by scripts/make-config.mjs — do not edit by hand.
// Regenerate: cd bird-count-backend && make web-config ENV=<env>
// For local dev: make web-config ENV=dev LOCAL=1
export const config = {
  apiBaseURL: ${JSON.stringify(apiBaseURL)},
  hostedUIDomain: ${JSON.stringify(hostedUIDomain)},
  webClientId: ${JSON.stringify(webClientId)},
  redirectURI: ${JSON.stringify(redirectURI)},
};
`;

const out = join(__dirname, '../js/config.js');
writeFileSync(out, src);
console.log(`Wrote js/config.js  redirectURI=${redirectURI}`);
