# Snapfile for BirdCount App Store Screenshots

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro Max",
  "iPhone 16",
  "iPad Pro 13-inch (M4)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("BirdCount")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# Remove any previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot